name: "Coding Standards"

on:
  pull_request:
    branches:
      - "master"
    paths:
      - .github/workflows/lint.yml
      - composer.*
      - lib/**
      - phpcs.xml.dist
      - tests/**
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/lint.yml
      - composer.*
      - lib/**
      - phpcs.xml.dist
      - tests/**

jobs:
  coding-standards:
    uses: "doctrine/.github/.github/workflows/coding-standards.yml@4.0.0"
